
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: project-exchange-backend
    environment:
      - PORT=8080
      - DB_PATH=./data.db
      - SECRET_KEY=${SECRET_KEY:-your-super-secret-jwt-key-change-this-in-production}
    volumes:
      - backend_data:/root/data.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`0sokrat0.ru`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
      - "traefik.docker.network=dokploy-network"
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend.middlewares=backend-stripprefix"
    networks:
      - dokploy-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: project-exchange-frontend
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BACKEND_URL=https://0sokrat0.ru/api
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`0sokrat0.ru`) && !PathPrefix(`/api`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.docker.network=dokploy-network"
      - "traefik.http.routers.frontend-redirect.rule=Host(`www.0sokrat0.ru`)"
      - "traefik.http.routers.frontend-redirect.entrypoints=websecure"
      - "traefik.http.routers.frontend-redirect.tls.certresolver=letsencrypt"
      - "traefik.http.routers.frontend-redirect.middlewares=redirect-to-non-www"
      - "traefik.http.middlewares.redirect-to-non-www.redirectregex.regex=^https://www\\.(.+)"
      - "traefik.http.middlewares.redirect-to-non-www.redirectregex.replacement=https://$${1}"
      - "traefik.http.middlewares.redirect-to-non-www.redirectregex.permanent=true"
    networks:
      - dokploy-network

volumes:
  backend_data:
    driver: local

networks:
  dokploy-network:
    external: true