
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: project-exchange-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_PATH=./data.db
      - SECRET_KEY=${SECRET_KEY:-your-super-secret-jwt-key-change-this-in-production}
    volumes:
      - backend_data:/root/data.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - dokploy-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: project-exchange-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BACKEND_URL=http://backend:8080
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - dokploy-network

volumes:
  backend_data:
    driver: local

networks:
  dokploy-network:
    external: true